# Generated by Django 4.1.5 on 2023-09-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=200)),
                ('e_mail', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('phone', models.BigIntegerField(default='')),
                ('Age', models.IntegerField(default='')),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'teacher_tb',
            },
        ),
    ]
