# Generated by Django 4.1.5 on 2024-02-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_age_remove_teacher_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='e_mail',
            new_name='username',
        ),
    ]
