# Generated by Django 4.1.5 on 2024-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_name_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.BigIntegerField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=18),
        ),
    ]
