# Generated by Django 4.1.5 on 2024-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_username_teacher_age_teacher_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.BigIntegerField(default='', max_length=20),
        ),
    ]
