# Generated by Django 4.1.5 on 2024-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=200)),
                ('Email', models.CharField(default='', max_length=30)),
                ('gender', models.CharField(default='', max_length=30)),
                ('phone', models.BigIntegerField()),
                ('Age', models.CharField(max_length=10)),
                ('password', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'student_tb',
            },
        ),
    ]
